# Generated by Django 3.1.2 on 2020-10-08 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('level_up_point', models.PositiveIntegerField(verbose_name='level up point')),
                ('min_point', models.PositiveSmallIntegerField(help_text='point depends on the level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='min point')),
                ('max_point', models.PositiveSmallIntegerField(help_text='point depends on the level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='max point')),
            ],
            options={
                'verbose_name': 'Action Level',
                'verbose_name_plural': 'Action Levels',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='action')),
                ('point', models.SmallIntegerField(help_text='points depend on the level of the action', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='point')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='actions.actionlevel', verbose_name='level')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'unique_together': {('name', 'level')},
            },
        ),
    ]
