# Generated by Django 3.1.2 on 2020-10-08 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('level_up_point', models.PositiveIntegerField(verbose_name='level up point')),
            ],
            options={
                'verbose_name': 'User Level',
                'verbose_name_plural': 'User Levels',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='total points')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstatus', to='rewards.userlevel', verbose_name='level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userstatus', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Status',
                'verbose_name_plural': 'Users Statuses',
                'db_table': 'userstatus',
            },
        ),
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_earned', models.SmallIntegerField(blank=True, null=True, verbose_name='point earned')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useractions', to='actions.action', verbose_name='action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useractions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Action',
                'verbose_name_plural': 'User Actions',
                'db_table': 'useractions',
            },
        ),
    ]
